language: perl

sudo: false

matrix:
  include:
    - perl: "5.30"
      env:
        ALIEN_INSTALL_TYPE=share
    - perl: "5.30"
      env:
        ALIEN_INSTALL_TYPE=default
    - perl: "5.30"
      env:
        - ALIEN_INSTALL_TYPE=system
        - LIBDEFLATE_SYSTEM_VERSION=1.0
    - perl: "5.26"
    - perl: "5.14"
      dist: trusty
    - perl: "5.26"
      os: osx
      osx_image: xcode7.3
    - language: c
      os: windows
      env:
        - TRAVIS_PERL_VERSION="5.30.0_64"
        - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
        - BERRYBREW_V1_24_IN_CHOCO=false
        
before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      eval "$($HOME/perl5/perlbrew/bin/perlbrew env $TRAVIS_PERL_VERSION)"
      export PATH=${PERLBREW_PATH:-$PERLBREW_ROOT/bin}:$PATH
      perlbrew --quiet install-cpanm --force
      cpanm --version
      env | grep -i ^perl
      export SSL_DIR=/usr/local/Cellar/openssl/1.0.2j
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      env | grep -i ^TRAVIS
      if [[ "$BERRYBREW_V1_24_IN_CHOCO" == "true" ]]; then
        choco install berrybrew
      else
        git clone -b v1.24 https://github.com/stevieb9/berrybrew
        cd berrybrew
        rm bin/berrybrew.exe
        export PATH="$MSBUILD_PATH:$MSBUILD_PATH\Roslyn:$PATH"
        # MSBuild.exe -nologo -p:Configuration=Release;Platform=x64 berrybrew.csproj
        csc.exe -lib:bin -t:library -r:Newtonsoft.Json.dll,ICSharpCode.SharpZipLib.dll -out:bin/bbapi.dll src/berrybrew.cs
        csc.exe -lib:bin -r:bbapi.dll -out:bin/berrybrew.exe -win32icon:inc/berrybrew.ico src/bbconsole.cs
        ./bin/berrybrew.exe config
      fi
      berrybrew install $TRAVIS_PERL_VERSION
      berrybrew switch $TRAVIS_PERL_VERSION
      which perl
      perl --version
    fi
  - |
    if [[ "$ALIEN_INSTALL_TYPE" == "system" ]]; then
      curl -Lo $HOME/libdeflate.tar.gz https://github.com/ebiggers/libdeflate/archive/v${LIBDEFLATE_SYSTEM_VERSION}.tar.gz
      tar -C $HOME -zxf $HOME/libdeflate.tar.gz
      make -C $HOME/libdeflate-${LIBDEFLATE_SYSTEM_VERSION} libdeflate.a gzip gunzip checksum CFLAGS=-fPIC
      export ALIEN_LIBDEFLATE_PROBE_CFLAGS=-I$HOME/libdeflate-${LIBDEFLATE_SYSTEM_VERSION}
      export ALIEN_LIBDEFLATE_PROBE_LDFLAGS=-L$HOME/libdeflate-${LIBDEFLATE_SYSTEM_VERSION}
    fi

install:
  - cpanm --with-develop --installdeps -n -q .
